### ISSUE TITLE
musl/alpine support

### ISSUE THREAD

**Issue by dequis** [alttch/pptop#1]
Hey there! Wonderful tool, love it, been looking for something like this for years.

I had to make a slight tweak to make it work with alpine / musl libc (which is fairly common in docker containers).

The call to `__libc_dlopen_mode()` is glibc specific (as far as i can see, a workaround for the fact that libdl is not always loaded?), with musl you should just do `dlopen()`.

I don't have a clean patch for this (that doesn't break glibc and tries to detect musl somehow), but wanted to post the issue to not forget.

Cheers

**Comment by divi255** [comment]
it seems it works fine with dlopen in glibc as well. fixed in 0.5.12

p.s. thanks for the feedback )
